/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reservation = IDL.Record({
  'customerName' : IDL.Text,
  'serviceName' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'submitReservation' : IDL.Func([Reservation], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reservation = IDL.Record({
    'customerName' : IDL.Text,
    'serviceName' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'submitReservation' : IDL.Func([Reservation], [], []),
  });
};

export const init = ({ IDL }) => { return []; };